### PR TITLE
add set(CMAKE_CXX_FLAGS "-fcoroutines") in CMakeLists.txt

### PR DESCRIPTION
**Pull request by yunwei37**
resolving the issue #25

### CODE REVIEW

**Comment by CarterLi** [comment]
What about clang?

**Comment by yunwei37** [comment]
I'm sorry I forgot that before...

This can be compiled by my Clang 10.0.0 on the same ubuntu 20.04, both g++ and clang pass the two tests in `ctest --test-dir build`.

**Comment by CarterLi** [comment]
可以 👍

**Comment by insujang** [comment]
I cannot build it with clang12, saying:
```
c++: error: unrecognized command line option '-fcoroutines'
```

Should this include another compiler ID check for clang?

**Comment by insujang** [comment]
~~I cannot compiled this:~~
```
c++: error: unrecognized command line option '-fcoroutines'
```
~~Should this include another compiler ID check for clang?~~

Sorry, my mistake. Should set which compiler to use manually with `-DCMAKE_CXX_COMPILER`, not using build.sh.

**Pull request merged**
