### PR TITLE
Refactor async

### PR DESCRIPTION
**Pull request by codeinred**
Hi Carter,

I restructured the project so that library files go in `include/`, and I also added a CMakeLists.txt so that the project can be built with CMake! I also added a script `build.sh` as a convenience script to run the build process with CMake. I also configured things so that CMake will automatically download and link against libfmt as part of the build process, if it's not present on the system (this means it doesn't need to be included as a git module)

Please let me know what you think!

Also: I noticed that the default branch is `async` rather than `master` - is there a reason for that?

### CODE REVIEW

**Comment by CarterLi** [comment]
> Hi Carter,
> 
> I restructured the project so that library files go in `include/`, and I also added a CMakeLists.txt so that the project can be built with CMake! I also added a script `build.sh` as a convenience script to run the build process with CMake. I also configured things so that CMake will automatically download and link against libfmt as part of the build process, if it's not present on the system (this means it doesn't need to be included as a git module)

At the time I started this project, I got link errors compiling liburing4cpp with clang++, libc++ and system libfmt. It seems that it's fine now.

> 
> Please let me know what you think!
> 
> Also: I noticed that the default branch is `async` rather than `master` - is there a reason for that?

The master branch uses third party stackful coroutines library instead of the stackless C++20 coroutines, and due to bug #9 it's still being maintained.

**Comment by CarterLi** [comment]
I got following error:

```
CMake Error at functions.cmake:9 (if):
  if given arguments:

    "liburing4cpp" "STREQUAL"

  Unknown arguments specified
Call Stack (most recent call first):
  CMakeLists.txt:16 (include)
```

`cmake version 3.18.4`

**Comment by codeinred** [comment]
Thank you so much for catching that! I'm so incredibly sorry to have made that mistake! `PROJECT_NAME` should have been in all caps. I'd tested the code, but cmake never ran that line because in version 3.21 `PROJECT_IS_TOP_LEVEL` is a built-in variable, so the if statement never got checked.

I fixed the error and downloaded an older version of cmake. The bug is gone now. Please try pulling again!

**Comment by codeinred** [comment]
I added two more small fixes. The build worked, but if you included this project as a dependency of another cmake project, it was building all of the demo files even though it should only have included the library. These changes fix that, so that when you include this project as a dependency, the demo files won't get built.

**Comment by codeinred** [comment]
> At the time I started this project, I got link errors compiling liburing4cpp with clang++, libc++ and system libfmt. It seems that it's fine now.
One of the features included in the cmake file in this pull request is the option to fetch `libfmt` from github and link against that, rather than linking against the system fmt. If you pass `-DALWAYS_FETCH=ON` to either cmake or `build.sh`, then it'll link statically against a version downloaded from github. This version will be placed in `build/_deps`.

```bash
./build.sh -DALWAYS_FETCH=ON
```
This uses [cmake FetchContent](https://cmake.org/cmake/help/latest/module/FetchContent.html), and so you don't need to have `fmt` as a git submodule.

Alternatively, if you'd prefer to continue to `fmt` as a git submodule, then we can use `add_subdirectory(fmt)`

**Comment by CarterLi** [comment]
Thanks

**Comment by CarterLi** [comment]
Did you use a tool to create `functions.cmake`?

**Comment by codeinred** [comment]
I wrote it from scratch to contain useful helper functions, so that I could make my CMakeLists.txt shorter and more consistent between projects. The main things it adds are:

- It defines `PROJECT_IS_TOP_LEVEL` for older versions of cmake, which is useful if you don't want to build tests when your library is used as a submodule
- It defines `note`, which is like the built-in `message` function, except it colors the message to make it stand out (I noticed without highlighting sometimes the output of `message` got lost, since cmake prints a ton of stuff)
- It defines `find_or_fetch`, which checks if a package exists and downloads it if it can't find it (this is what's used to automatically download `fmt`)
- It defines `add_source_dir`, which will add every top-level `cpp` file in a directory as a target
- It defines `target_cpp_20`, which specifies that an interface library should be built using C++20. It also adds `-fcoroutines` for gcc and defines `__cpp_impl_coroutine` for clang, which is needed to build coroutines on those compilers when using the gcc version of the C++ standard library.

Copy-pasting all of those functions into a CMakeLists.txt makes it hard to see what's going on with the actual build, which is why I moved them into their own file

**Pull request merged**
